GET http://localhost:8080/products
# get all

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "category": "storage drive",
  "description": "lorem all the way",
  "img": ["https://cdn.pixabay.com/photo/2021/10/30/17/33/cappadocia-6755061__340.jpg","https://cdn.pixabay.com/photo/2013/08/10/17/03/animal-171318_960_720.jpg"],
  "name": "WD-nvme500",
  "price": 100
}

###

DELETE http://localhost:8080/products/618ad98eaf32b321cc8175eb

###
PATCH http://localhost:8080/products/61896b51739e3b024ac9f9fc
Content-Type: application/json

{
  "price": 1001
}

###

PATCH http://localhost:8080/shopCart
Content-Type: application/json

{
  "name": "koka"
}

###

POST http://localhost:8080/contact
Content-Type: application/json

{
  "message": "ma kore"
}

###

GET http://localhost:8080/contacts

###

DELETE   http://localhost:8080/cartProduct/619044809d8908f308887e1f

###

GET http://localhost:8080/shopCart


